debug = true

[connection]
ip = "127.0.0.1" # ipv4 of the MCU, only used in wifi mode and iot mode
pwd = "liyuan11328"
# mode = "wired" deprecated
retry = 5 # how many times it tries when Connection Errors occuring 
retry_interval = 0.8 # secs


# pwd = "liyuan11328" # if necassary

[iot]
public_key = "public key demo"
private_key = "123456"



