debug = false

[connection]
ip = "192.168.244.122" # ipv4 of the MCU, only used in wifi mode and iot mode
port = 8081
pwd = "liyuan11328"
retry = 5 # how many times it tries when Connection Errors occuring 
retry_interval = 1.8 # secs


# pwd = "liyuan11328" # if necassary

[iot]
device_id = "660d43201b5757626c1b700f_0403demo"
device_secret = "123456"



